INSERT INTO `[#DB_PREFIX#]system_setting` (`id`, `varname`, `desc`, `groupid`, `sort`, `type`, `value`, `status`) VALUES
(20, 'site_name', '网站名称', 1, 0, 'string', 's:7:"Anwsion";', 0),
(21, 'description', '网站简介', 1, 0, 'textarea', 's:29:"Anwsion 是一个问答社区";', 0),
(26, 'answer_open', '用户是否允许回复问题', 99, 0, 'bool', 's:1:"Y";', -1),
(23, 'site_open', '关闭维护网站', 99, 0, 'bool', 's:1:"N";', -1),
(24, 'close_notice', '关闭维护提示', 99, 0, 'textarea', 's:36:"系统维护中，请稍候访问。";', -1),
(22, 'keywords', '关键词(以逗号隔开)', 1, 0, 'textarea', 's:20:"Anwsion,问题社区";', 0),
(27, 'sensitive_words', '敏感词', 99, 1, 'textarea', 's:59:"江泽民\n胡锦涛\n温家宝\n周永康\n习近平\n李国强";', -1),
(28, 'def_focus_uids', '用户注册后默认关注的用户 ID', 4, 0, 'string', 's:1:"1";', 0),
(29, 'question_edit_time', '问题编辑限制时间 (单位:分钟)', 4, 0, 'int', 's:2:"30";', 0),
(31, 'answer_edit_time', '回复编辑限制时间 (单位:分钟)', 4, 0, 'int', 's:2:"30";', 0),
(33, 'cache_level_high', '缓存高级别缓存时间 (单位:秒)', 10, 2, 'int', 's:2:"60";', 0),
(34, 'cache_level_normal', '缓存普通级别缓存时间 (单位:秒)', 10, 3, 'int', 's:3:"600";', 0),
(35, 'cache_level_low', '缓存低级别缓存时间 (单位:秒)', 10, 4, 'int', 's:4:"1800";', 0),
(36, 'unread_flush_interval', '未读数刷新间隔时间(秒)', 4, 0, 'int', 's:3:"100";', 0),
(37, 'newer_invitation_num', '新注册用户获得邀请额', 4, 0, 'int', 's:1:"5";', 0),
(38, 'index_per_page', '内容列表分页数 (首页, 最新动态)', 5, 2, 'int', 's:2:"20";', 0),
(41, 'cache_open', '开启系统缓存', 10, 1, 'bool', 's:1:"N";', 0),
(66, 'notifications_per_page', '内容列表分页数 (通知)', 5, 3, 'int', 's:2:"10";', 0),
(43, 'online_interval', '在线会员统计时间范围(单位:分钟)', 4, 0, 'int', 's:2:"15";', 0),
(44, 'online_count_open', '开启统计在线会员', 3, 0, 'bool', 's:1:"Y";', 0),
(45, 'smtp_server', 'SMTP 服务器 (如: smtp.163.com)', 6, 2, 'string', 's:0:"";', 0),
(46, 'smtp_username', 'SMTP 帐户', 6, 4, 'string', 's:0:"";', 0),
(47, 'stmp_password', 'SMTP 密码', 6, 5, 'string', 's:0:"";', 0),
(48, 'from_email', '邮件来源邮箱地址', 6, 6, 'string', '[#FROM_EMAIL#]', 0),
(49, 'index_sort', '首页显示模式', 99, 0, 'select', 's:1:"1";', -1),
(50, 'base_url', '网站首页 (最后不带 /)', 2, 0, 'string', '[#BASE_URL#]', 0),
(51, 'img_url', 'static 目录资源 URL 地址 (最后不带 /, 留空使用根目录下的 static 资源)', 2, 0, 'string', 's:0:"";', 0),
(52, 'upload_url', '上传目录外部访问 URL 地址', 2, 0, 'string', '[#UPLOAD_URL#]', 0),
(53, 'upload_dir', '上传文件存放绝对路径', 2, 0, 'string', '[#UPLOAD_DIR#]', 0),
(54, 'smtp_port', 'SMTP 端口', 6, 3, 'int', 's:2:"25";', 0),
(55, 'ui_style', '用户界面风格', 3, 2, 'select', 's:7:"default";', 0),
(56, 'email_type', '系统邮件发送方式', 6, 1, 'select', 's:1:"2";', 0),
(57, 'uninterested_fold', '不感兴趣数达到多少个时折叠回复', 4, 1, 'int', 's:1:"5";', 0),
(58, 'hot_user_period', '热门用户计算周期(单位:天)', 4, 0, 'int', 's:1:"7";', 0),
(59, 'sina_akey', '新浪微博 AppKey(akey)', 7, 0, 'string', 's:0:"";', 0),
(60, 'sina_skey', '新浪微博 AppKey(skey)', 7, 0, 'string', 's:0:"";', 0),
(61, 'qq_app_key', '腾讯微博 AppKey(app_key)', 7, 0, 'string', 's:0:"";', 0),
(62, 'qq_app_secret', '腾讯微博 AppKey(app_secret)', 7, 0, 'string', 's:0:"";', 0),
(63, 'sina_weibo_enabled', '开启新浪微博功能', 7, 0, 'bool', 's:1:"N";', 0),
(64, 'qq_t_enabled', '开启腾讯微博功能', 7, 0, 'bool', 's:1:"N";', 0),
(65, 'answer_unique', '只允许用户对每个问题回答一次', 3, 0, 'bool', 's:1:"Y";', 0),
(67, 'contents_per_page', '内容列表分页数 (问题, 发现, 个人主页)', 5, 4, 'int', 's:2:"10";', 0),
(68, 'guest_explorer', '是否允许游客访问发现页面', 3, 0, 'bool', 's:1:"Y";', 0),
(69, 'hot_question_period', '热门问题计算周期(单位:天)', 4, 0, 'int', 's:2:"30";', 0),
(70, 'category_display_mode', '分类显示模式', 3, 0, 'select', 's:4:"list";', 0),
(71, 'recommend_users_number', '推荐用户和话题数量', 3, 0, 'int', 's:1:"6";', 0),
(72, 'ucenter_enabled', '开启 Ucenter 用户对接', 3, 0, 'bool', 's:1:"N";', 0);
